spring:
  h2:
    console:
      enabled: true
  profiles:
    active: test
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    #    We'll just use in-memory database
    #    url: jdbc:mysql://localhost:3306/crud_todo?useSSL=false&createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
